parameters:
      - name: webapp
        type: string
        default: 'insight-webapp'
      - name: apptype
        type: string
        default: 'webApp'
      - name: azureSubscription
        type: string
        default: 'Free Trial (180be318-3bda-484b-9b28-27ffcbe8b622)'      


 steps:
 - task: DownloadPipelineArtifact@2
   inputs:
   buildType: 'current'
   buildVersionToDownload: 'latest'
   targetPath: '$(build.artifactstagingdirectory)'
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: insight-webapp'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    appType: ${{parameters.apptype}}
    appName: ${{parameters.webapp}}
