
stages:
- stage: CI
  jobs:
  - job: Job_1
    displayName:  Build Agent 
    pool:
      vmImage: 'windows-latest'

 steps:
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: insight-webapp'
  inputs:
    azureSubscription: 'Free Trial (180be318-3bda-484b-9b28-27ffcbe8b622)'
    appType: webApp
    appName: 'insight-webapp'
