
trigger: none
stages:
- stage: CI
  jobs:
  - job: Job_1
    displayName:  Build Agent 
    pool:
      vmImage: 'windows-latest'
   
    extends:
     template: .Net-CI.yaml

- stage: CD
  dependsOn: CI
  jobs:
  - job: Job_2
    displayName: Deploy Agent 
    pool:
       vmImage: 'windows-latest'
   
    extends:
     template: .Net-CD.yaml


  
  
  

  

