

trigger: none


jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: https://raw.githubusercontent.com/balaji-9702/Templates/main/.Net-CI.yaml
  - template: https://raw.githubusercontent.com/balaji-9702/Templates/main/.Net.CD.yaml

  
  
  

  

