resources:
  repositories:
  - repository: Templates
    type: git
    endpoint: Mygit
    name: balaji-9702/Templates
    ref: main
   


trigger: none


jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: Templates
  - template: .Net-CI.yaml
  - template: .Net-CD.yaml
  
  
  

  

