resources:
  repositories:
  - repository: Templates
    type: git
    endpoint: Mygit
    name: Templates
    ref: main
   


trigger: none


jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  
  - template: Templates/.Net-CI.yaml
  - template: Templates/.Net-CD.yaml
  
  
  

  

