


resources:
  repositories:
  - repository: MyGitHubRepo
    type: github
    endpoint: Mygit
    name: balaji-9702/Templates
    ref : main
  
trigger: none

variables:
- template: values.yaml

jobs:
- job: Build
  condition:  eq('${{ variables.BuildtechBackend }}', 'Net')
  pool:
    vmImage: ${{ variables.vmImage }}
  steps: 
  - script:  echo "${{ variables.BuildtechBackend }}"
  - template: Templates/.Net-CI.yaml
  - template: Templates/.Net-CD.yaml
  

- job: PythonDeploy
  condition: and(succeeded(), eq('${{ variables.BuildtechBackend }}', 'python'))
  pool:
    vmImage: ${{ variables.vmImage }}
  steps:
  - checkout: MygithubRep
  - template: $(Build.SourcesDirectory)/python-CI.yaml
  - script: echo "hi"
  
  

  
  
  
  

  

