

trigger: none


jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - source: https://github.com/balaji-9702/Templates/blob/main/.Net-CI.yaml
  - source: https://github.com/balaji-9702/Templates/blob/main/.Net.CD.yaml
  
  
  

  

