
trigger: none

extends:
  template: .Net-CI.yaml
  

- stage: CD
  jobs:
  - job: Job_1
    displayName:  Build Agent 
    pool:
      vmImage: 'windows-latest' 
    steps:
     template: .Net-CD.yaml
