resources:
  repositories:
  - repository: Templates
    type: git
    endpoint: Mygit
    name: Templates
    ref: main
   


trigger: none


jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  
  - template: .Net-CI.yaml@Templates
  - template: .Net-CD.yaml@Templates
  
  
  

  

