resources:
  repositories:
  - repository: Templates
    type: git
    name: Templates
    
   


trigger: none


jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  
  - template: .Net-CI.yaml
  - template: .Net-CD.yaml
  
  
  

  

