

variables:
- name: repository
  value: MygitHubRepo
- name: type
  value: github
- name: endpoint
  value: Mygit
- name: name
  value: balaji-9702/Templates
- name: vmImage
  value: windows-latest
  
